# Generated by Django 4.2.11 on 2024-11-22 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_don_vi', models.CharField(max_length=100)),
                ('cap_do', models.CharField(choices=[('tong', 'Tổng'), ('trung_doan', 'Trung đoàn'), ('dai_doi', 'Đại đội'), ('tieu_doi', 'Tiểu đội'), ('hau_can', 'Hậu cần')], max_length=20)),
                ('dashboard_template', models.CharField(default='dashboard.html', max_length=50)),
                ('don_vi_cha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='appQLQT.donvi')),
                ('quan_li', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_kho', models.CharField(max_length=100)),
                ('don_vi', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kho', to='appQLQT.donvi')),
                ('quan_li_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_kho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuCapPhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_cap_phat', models.PositiveIntegerField()),
                ('ngay_cap_phat', models.DateField(auto_now_add=True)),
                ('da_nhan', models.BooleanField(default=False)),
                ('don_vi_giao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_vi_giao', to='appQLQT.donvi')),
                ('don_vi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_vi_nhan', to='appQLQT.donvi')),
            ],
        ),
        migrations.CreateModel(
            name='QuanTuTrang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_qtt', models.CharField(max_length=100)),
                ('loai_qtt', models.CharField(max_length=50)),
                ('kich_co', models.CharField(blank=True, max_length=20)),
                ('mo_ta', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuanNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('so_bien_nhan', models.CharField(max_length=50)),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.donvi')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('so_luong_xuat', models.PositiveIntegerField()),
                ('ngay_xuat', models.DateField(auto_now_add=True)),
                ('don_vi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.donvi')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.kho')),
                ('quan_tu_trang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.quantutrang')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuXacNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_xac_nhan', models.BooleanField(default=False)),
                ('don_vi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.donvi')),
                ('phieu_cap_phat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.phieucapphat')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('so_luong_nhap', models.PositiveIntegerField()),
                ('ngay_nhap', models.DateField(auto_now_add=True)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.kho')),
                ('quan_tu_trang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.quantutrang')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_nhan', models.PositiveIntegerField()),
                ('ngay_nhan', models.DateField(auto_now_add=True)),
                ('don_vi_giao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phieunhan_giao', to='appQLQT.donvi')),
                ('don_vi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieunhan_nhan', to='appQLQT.donvi')),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.phieuxuat')),
            ],
        ),
        migrations.AddField(
            model_name='phieucapphat',
            name='quan_tu_trang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.quantutrang'),
        ),
        migrations.CreateModel(
            name='KhoQuanTrang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.kho')),
                ('quan_tu_trang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.quantutrang')),
            ],
            options={
                'unique_together': {('kho', 'quan_tu_trang')},
            },
        ),
        migrations.CreateModel(
            name='DonViQuanTrang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.donvi')),
                ('quan_tu_trang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQLQT.quantutrang')),
            ],
            options={
                'unique_together': {('don_vi', 'quan_tu_trang')},
            },
        ),
    ]
