# Generated by Django 4.2.11 on 2024-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQLQT', '0002_alter_donvi_cap_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donvi',
            name='cap_do',
            field=models.CharField(choices=[('tong', 'Kho'), ('tieu_doan', 'Tiểu đoàn'), ('trung_doi', 'Trung đội'), ('dai_doi', 'Đại đội')], max_length=20),
        ),
    ]
