# Generated by Django 4.2.11 on 2024-11-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQLQT', '0003_alter_donvi_cap_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='donvi',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
