# Generated by Django 4.2.11 on 2024-11-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQLQT', '0007_alter_donvi_cap_do_alter_userprofile_cap_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='don_vi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='appQLQT.donvi'),
        ),
    ]
