# Generated by Django 4.2.11 on 2024-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQLQT', '0009_alter_donvi_cap_do_alter_userprofile_cap_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantutrang',
            name='mo_ta',
        ),
        migrations.AddField(
            model_name='quantutrang',
            name='ma_qtt',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
