# Generated by Django 4.2.11 on 2024-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQLQT', '0012_alter_quantutrang_ma_qtt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantutrang',
            name='ma_qtt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
